- hosts: localhost
  connection: local
  gather_facts: False
  roles:
   - { role: aws, tags: [ "aws" ] }


- hosts: all
  gather_facts: True
  roles:
    - { role: bootstrap, tags: [ "bootstrap" ] }

- hosts: all
  gather_facts: True
  roles:
    - { role: common, tags: [ "common" ] }
    - { role: nginx, tags: [ "nginx" ] }
    - { role: deploy, tags: [ "deploy" ] }


